version: '1'
services:
  blockmesh:
    image: aron666/blockmesh
    environment:
      - BM_EMAIL=email
      - BM_PASS=password
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
    ports:
      - 5002:8080
    build: 
      context: .
      dockerfile: Dockerfile
